¡ɐpqɯɐl ʎɹǝʌ 'lɐuoᴉʇɔunɟ ǝɹoW
WeixuanZ/dataopen2020 pull request #7
Opened 2020-10-26 23:28 UTC by DaveDuck321

Pls test, filter >> map

Full patch or nothing. thanks.

Your welcome,

2020-10-27 00:43 UTC, WeixuanZ commented
Thx bro

2020-10-27 00:58 UTC, WeixuanZ requested changes

2020-10-27 00:58 UTC, WeixuanZ commented on src/prediction.py
> +len(filter(
No filters plz 👻

2020-10-28 00:16 UTC, DaveDuck321 commented on src/prediction.py
> +len(filter(
Fixed! more functions make it better

2020-10-28 00:17 UTC, WeixuanZ approved these changes
ಠ_ರೃ

2020-10-28 00:33 UTC, merged